#ifndef __INTELLISENSE__

extern "C" size_t __base_address = 0x6B30000;
extern "C" void _sub_6B6A343();
extern "C" void* __entry_ptr = reinterpret_cast<void*>(&_sub_6B6A343);
#pragma comment(linker, "/export:??0CDPClientProxy@@QAE@ABV0@@Z=_sub_6B38B60,@1")
#pragma comment(linker, "/export:??0CDPMsgList@@QAE@ABV0@@Z=_sub_6B38940,@2")
#pragma comment(linker, "/export:??0CDPServer@@QAE@ABV0@@Z=_sub_6B38E10,@3")
#pragma comment(linker, "/export:??0IClient@@QAE@ABV0@@Z=_sub_6B322A0,@4")
#pragma comment(linker, "/export:??0IClient@@QAE@XZ=_sub_6B32290,@5")
#pragma comment(linker, "/export:??0IDPMsgHandler@@QAE@ABV0@@Z=_sub_6B38920,@6")
#pragma comment(linker, "/export:??0IDPMsgHandler@@QAE@XZ=_sub_6B38910,@7")
#pragma comment(linker, "/export:??0IServerImpl@@QAE@ABU0@@Z=_sub_6B38890,@8")
#pragma comment(linker, "/export:??0IServerImpl@@QAE@XZ=_sub_6B38870,@9")
#pragma comment(linker, "/export:??4CDPClientProxy@@QAEAAV0@ABV0@@Z=_sub_6B38C60,@10")
#pragma comment(linker, "/export:??4CDPMsgList@@QAEAAV0@ABV0@@Z=_sub_6B389F0,@11")
#pragma comment(linker, "/export:??4CDPServer@@QAEAAV0@ABV0@@Z=_sub_6B38F70,@12")
#pragma comment(linker, "/export:??4IClient@@QAEAAV0@ABV0@@Z=_sub_6B322B0,@13")
#pragma comment(linker, "/export:??4IDPMsgHandler@@QAEAAV0@ABV0@@Z=_sub_6B38930,@14")
#pragma comment(linker, "/export:??4IServerImpl@@QAEAAU0@ABU0@@Z=_sub_6B388C0,@15")
#pragma comment(linker, "/export:??_7CDPClientProxy@@6B@=_off_6B6BB64,@16")
#pragma comment(linker, "/export:??_7CDPMsgList@@6B@=_off_6B6BB60,@17")
#pragma comment(linker, "/export:??_7CDPServer@@6B@=_off_6B6BB78,@18")
#pragma comment(linker, "/export:??_7IClient@@6B@=_off_6B6B3B0,@19")
#pragma comment(linker, "/export:??_7IDPMsgHandler@@6B@=_off_6B6BB50,@20")
#pragma comment(linker, "/export:??_7IServerImpl@@6BIChatServer@@@=_off_6B6B864,@21")
#pragma comment(linker, "/export:??_7IServerImpl@@6BIServer@@@=_off_6B6B868,@22")
#pragma comment(linker, "/export:?ForceClientLogout@@YAXI@Z=_sub_6B39CB0,@23")
#pragma comment(linker, "/export:?GetClientStats@@YAHPAUclient_stats_t@@PAH@Z=_sub_6B39BA0,@24")
#pragma comment(linker, "/export:?GetNumClients@@YAHXZ=_sub_6B39B90,@25")
#pragma comment(linker, "/export:?GetRemoteClientPort@@YAXAAV?$vector@KV?$allocator@K@std@@@std@@@Z=_sub_6B39C90,@26")
#pragma comment(linker, "/export:?OnAddHost@IDPMsgHandler@@UAEXPAU_DPNMSG_ENUM_HOSTS_RESPONSE@@@Z=_sub_6B38900,@27")
#pragma comment(linker, "/export:?OnConnect@IDPMsgHandler@@UAEXJ@Z=_sub_6B388E0,@28")
#pragma comment(linker, "/export:?OnDisconnect@IDPMsgHandler@@UAEXXZ=_sub_6B388F0,@29")
#pragma comment(linker, "/export:?OnReceive@IDPMsgHandler@@UAEXPAEK@Z=_sub_6B388D0,@30")
#pragma comment(linker, "/export:?SetRemoteClientPassword@@YAXPBG@Z=_sub_6B39BE0,@31")
#pragma comment(linker, "/export:?SetRemoteClientResponseData@@YAX_N0HPBGIPBD@Z=_sub_6B39C00,@32")
#pragma comment(linker, "/export:?SetRemoteClientSessionName@@YAXPBG@Z=_sub_6B39BC0,@33")
#pragma comment(linker, "/export:?SetServerLogFunction@@YAXP6AHUErrorCode@@PBDZZ@Z=_sub_6B39560,@34")
#pragma comment(linker, "/export:Client=_data_6B73B28,@35")
#pragma comment(linker, "/export:GetChatClientInterface=_sub_6B394F0,@36")
#pragma comment(linker, "/export:GetClientInterface=_sub_6B394E0,@37")

#endif // __INTELLISENSE__
